import type { Exercise } from './types'

export const EXERCISES: Exercise[] = [

  // ─── CHEST ─────────────────────────────────────────────────────────────

  {
    id: 'incline-bb-press',
    name: 'Incline Barbell Press',
    target: ['upper-chest', 'chest'],
    secondary: ['front-delts', 'triceps'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    tier: 'S',
    hypertrophyRating: 9,
    stimulusToFatigue: 7,
    description: 'The gold standard for upper chest development. Targets the clavicular head of the pectoralis major with heavy compound loading.',
    executionNotes: [
      'Set bench to 30-45°. Higher angles shift stress to delts.',
      'Use a shoulder-width or slightly wider grip.',
      'Lower bar to upper chest with 3-second eccentric.',
      'Drive through the middle of your chest, not just your arms.',
      'Retract and depress shoulder blades throughout.',
    ],
    alternatives: ['incline-db-press', 'incline-smith-press', 'landmine-press'],
    tags: ['compound', 'upper-chest', 'push', 'strength'],
    videoKeyword: 'incline barbell bench press tutorial',
  },

  {
    id: 'incline-db-press',
    name: 'Incline Dumbbell Press',
    target: ['upper-chest', 'chest'],
    secondary: ['front-delts', 'triceps'],
    equipment: ['dumbbell'],
    difficulty: 'intermediate',
    tier: 'S',
    hypertrophyRating: 9,
    stimulusToFatigue: 8,
    description: 'Superior stretch and range of motion versus barbell. Excellent upper chest builder with shoulder-friendly mechanics.',
    executionNotes: [
      'Allow elbows to flare out 60-75° (not 90°).',
      'Stretch fully at the bottom — feel the chest load.',
      'Touch dumbbells gently at the top, maintain tension.',
      'Use slow eccentric (3s down) for maximum hypertrophy.',
    ],
    alternatives: ['incline-bb-press', 'incline-cable-fly', 'incline-machine-press'],
    tags: ['compound', 'upper-chest', 'push', 'dumbbell'],
    videoKeyword: 'incline dumbbell press hypertrophy',
  },

  {
    id: 'flat-bb-press',
    name: 'Flat Barbell Bench Press',
    target: ['chest'],
    secondary: ['front-delts', 'triceps'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    tier: 'A',
    hypertrophyRating: 8,
    stimulusToFatigue: 6,
    description: 'Foundational chest mass builder. High mechanical tension with heavy loads.',
    executionNotes: [
      'Arch your back naturally, feet planted.',
      'Lower bar to the lower half of your chest.',
      'Flare elbows 45-60°, not 90°.',
      'Leg drive helps maintain tightness.',
    ],
    alternatives: ['flat-db-press', 'smith-bench', 'chest-press-machine'],
    tags: ['compound', 'chest', 'push', 'strength'],
    videoKeyword: 'bench press form guide',
  },

  {
    id: 'flat-db-press',
    name: 'Flat Dumbbell Press',
    target: ['chest'],
    secondary: ['front-delts', 'triceps'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    tier: 'A',
    hypertrophyRating: 8,
    stimulusToFatigue: 7,
    description: 'Greater range of motion than barbell bench. Excellent for chest thickness and symmetry.',
    executionNotes: [
      'Start with dumbbells at shoulder level.',
      'Lower slowly, feel the full stretch at the bottom.',
      'Keep core tight and feet grounded.',
    ],
    alternatives: ['flat-bb-press', 'cable-fly', 'pec-deck'],
    tags: ['compound', 'chest', 'push', 'dumbbell'],
    videoKeyword: 'dumbbell bench press technique',
  },

  {
    id: 'cable-fly-high',
    name: 'High Cable Fly (Lower Chest)',
    target: ['lower-chest', 'chest'],
    secondary: ['front-delts'],
    equipment: ['cable'],
    difficulty: 'beginner',
    tier: 'S',
    hypertrophyRating: 9,
    stimulusToFatigue: 9,
    description: 'Best isolation for the lower/sternal chest. Constant tension through full ROM with peak contraction.',
    executionNotes: [
      'Set cables high (above shoulder).',
      'Lean slightly forward, slight elbow bend.',
      'Bring hands together crossing slightly at peak.',
      'Focus on squeezing the chest, not pulling with arms.',
      'Control the eccentric — resist the cable.',
    ],
    alternatives: ['pec-deck', 'cable-crossover', 'dip'],
    tags: ['isolation', 'chest', 'cable', 'stretch-mediated'],
    videoKeyword: 'cable fly chest isolation',
  },

  {
    id: 'cable-fly-low',
    name: 'Low Cable Fly (Upper Chest)',
    target: ['upper-chest', 'chest'],
    secondary: ['front-delts'],
    equipment: ['cable'],
    difficulty: 'beginner',
    tier: 'S',
    hypertrophyRating: 9,
    stimulusToFatigue: 9,
    description: 'Best isolation for the upper/clavicular chest. Excellent alternative or addition to incline pressing.',
    executionNotes: [
      'Set cables low (at or below hip level).',
      'Stand slightly forward, arms travelling upward arc.',
      'Hands meet at upper chest level.',
      'Feel the upper chest contract at peak.',
    ],
    alternatives: ['cable-fly-high', 'incline-db-fly', 'landmine-press'],
    tags: ['isolation', 'upper-chest', 'cable', 'stretch-mediated'],
    videoKeyword: 'low cable fly upper chest',
  },

  {
    id: 'pec-deck',
    name: 'Pec Deck / Machine Fly',
    target: ['chest'],
    secondary: ['front-delts'],
    equipment: ['machine'],
    difficulty: 'beginner',
    tier: 'A',
    hypertrophyRating: 8,
    stimulusToFatigue: 9,
    description: 'Machine-based fly with constant tension. Excellent for pump and finishing sets.',
    executionNotes: [
      'Adjust seat so handles align with mid-chest.',
      'Keep slight bend in elbows throughout.',
      'Squeeze hard at peak contraction — 1s pause.',
      'Resist on the way back, do not let it pull you.',
    ],
    alternatives: ['cable-fly-high', 'cable-fly-low', 'flat-db-fly'],
    tags: ['isolation', 'chest', 'machine', 'pump'],
    videoKeyword: 'pec deck machine fly',
  },

  {
    id: 'dip',
    name: 'Weighted Dip',
    target: ['chest', 'lower-chest'],
    secondary: ['triceps', 'front-delts'],
    equipment: ['bodyweight'],
    difficulty: 'intermediate',
    tier: 'A',
    hypertrophyRating: 8,
    stimulusToFatigue: 6,
    description: 'Compound chest/tricep movement. Wide grip and forward lean biases the chest.',
    executionNotes: [
      'Lean forward 15-20° to target chest over triceps.',
      'Lower until upper arms are parallel to ground.',
      'Wide grip emphasises chest.',
      'Use a weight belt when bodyweight is easy.',
    ],
    alternatives: ['cable-fly-high', 'chest-press-machine', 'flat-bb-press'],
    tags: ['compound', 'chest', 'triceps', 'bodyweight'],
    videoKeyword: 'chest dip technique',
  },

  // ─── BACK / LATS ────────────────────────────────────────────────────────

  {
    id: 'pull-up-weighted',
    name: 'Weighted Pull-Up',
    target: ['lats', 'back'],
    secondary: ['biceps', 'rear-delts', 'upper-back'],
    equipment: ['pull-up-bar'],
    difficulty: 'advanced',
    tier: 'S',
    hypertrophyRating: 10,
    stimulusToFatigue: 8,
    description: 'The single best back width exercise. Unmatched lat stretch and mechanical tension.',
    executionNotes: [
      'Use shoulder-width or slightly wider pronated grip.',
      'Start from dead hang — full stretch of the lats.',
      'Drive elbows down and back to initiate pull.',
      'Pull to chest/collarbone level.',
      '3-second eccentric is critical for hypertrophy.',
    ],
    alternatives: ['lat-pulldown', 'cable-pullover', 'assisted-pull-up'],
    tags: ['compound', 'back', 'lats', 'bodyweight', 'width'],
    videoKeyword: 'weighted pull up lat hypertrophy',
  },

  {
    id: 'lat-pulldown',
    name: 'Wide Grip Lat Pulldown',
    target: ['lats', 'back'],
    secondary: ['biceps', 'rear-delts'],
    equipment: ['cable'],
    difficulty: 'beginner',
    tier: 'S',
    hypertrophyRating: 9,
    stimulusToFatigue: 9,
    description: 'Best back width builder for most lifters. Allows precise load management and focus on lat contraction.',
    executionNotes: [
      'Use overhand grip slightly wider than shoulder-width.',
      'Lean back 10-15°, chest up, arch the upper back.',
      'Pull to upper chest — elbows drive down to sides.',
      'Stretch arms fully overhead at top.',
      'Squeeze lat at the bottom of each rep.',
    ],
    alternatives: ['pull-up-weighted', 'straight-arm-pulldown', 'single-arm-pulldown'],
    tags: ['compound', 'back', 'lats', 'cable', 'width'],
    videoKeyword: 'lat pulldown form hypertrophy',
  },

  {
    id: 'cable-row',
    name: 'Seated Cable Row',
    target: ['back', 'upper-back'],
    secondary: ['biceps', 'rear-delts', 'lats'],
    equipment: ['cable'],
    difficulty: 'beginner',
    tier: 'S',
    hypertrophyRating: 9,
    stimulusToFatigue: 8,
    description: 'King of back thickness. Excellent for mid and upper back density with constant cable tension.',
    executionNotes: [
      'Use neutral grip attachment (V-bar) for most lat involvement.',
      'Sit upright — slight forward lean at stretch, upright at contraction.',
      'Drive elbows past sides — retract shoulder blades at peak.',
      'Let scapula protract fully on each rep for max stretch.',
    ],
    alternatives: ['db-row', 'bb-row', 'machine-row'],
    tags: ['compound', 'back', 'cable', 'thickness'],
    videoKeyword: 'seated cable row back thickness',
  },

  {
    id: 'db-row',
    name: 'Single Arm Dumbbell Row',
    target: ['lats', 'back'],
    secondary: ['biceps', 'rear-delts'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    tier: 'A',
    hypertrophyRating: 9,
    stimulusToFatigue: 8,
    description: 'Excellent unilateral back exercise. Great ROM and the ability to load heavy.',
    executionNotes: [
      'Brace on bench, keep spine neutral.',
      'Pull elbow high toward hip — not armpit.',
      'Rotate torso slightly for full lat engagement.',
      'Full hang at the bottom for max stretch.',
    ],
    alternatives: ['cable-row', 'chest-supported-row', 'machine-row'],
    tags: ['compound', 'back', 'dumbbell', 'unilateral'],
    videoKeyword: 'dumbbell row lat technique',
  },

  {
    id: 'chest-supported-row',
    name: 'Chest Supported DB Row',
    target: ['upper-back', 'back'],
    secondary: ['rear-delts', 'biceps'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    tier: 'A',
    hypertrophyRating: 8,
    stimulusToFatigue: 9,
    description: 'Removes lower back from the equation. Excellent for upper back and rear delt hypertrophy.',
    executionNotes: [
      'Set incline bench to 30-45°.',
      'Lie chest-down, let arms hang fully.',
      'Row elbows up and back — squeeze rhomboids.',
      'Use a flared elbow path for upper back emphasis.',
    ],
    alternatives: ['cable-row', 'machine-row', 'pendlay-row'],
    tags: ['compound', 'back', 'upper-back', 'supported'],
    videoKeyword: 'chest supported row upper back',
  },

  {
    id: 'straight-arm-pulldown',
    name: 'Straight Arm Cable Pulldown',
    target: ['lats'],
    secondary: ['triceps', 'core'],
    equipment: ['cable'],
    difficulty: 'beginner',
    tier: 'S',
    hypertrophyRating: 9,
    stimulusToFatigue: 10,
    description: 'Pure lat isolation. Massive stretch at the top and strong contraction at bottom. Extremely high S:F ratio.',
    executionNotes: [
      'Set cable high, use rope or straight bar.',
      'Keep arms straight (slight elbow bend).',
      'Hinge at hips slightly, pull bar to thighs.',
      'Focus entirely on the lat — squeeze at bottom.',
      'Slow the return — that is where the growth is.',
    ],
    alternatives: ['lat-pulldown', 'pull-over-machine', 'cable-pull-over'],
    tags: ['isolation', 'lats', 'cable', 'stretch-mediated', 'width'],
    videoKeyword: 'straight arm pulldown lat',
  },

  // ─── NEW: VERTICAL TRACTION / OBLIQUE / LOWER BACK ─────────────────────

  {
    id: 'vertical-traction-machine',
    name: 'Vertical Traction Machine',
    target: ['lats', 'back'],
    secondary: ['rear-delts', 'biceps'],
    equipment: ['machine'],
    difficulty: 'beginner',
    tier: 'A',
    hypertrophyRating: 9,
    stimulusToFatigue: 8,
    description: 'Machine-based vertical traction simulating pull-up mechanics with precise loading and reduced technical demand.',
    executionNotes: [
      'Adjust chest pad and handles for full lat stretch at top.',
      'Pull shoulder blades down and together — lead with elbows.',
      'Control the eccentric for 2-3s on the return.',
    ],
    alternatives: ['lat-pulldown', 'pull-up-weighted', 'single-arm-pulldown'],
    tags: ['machine', 'lats', 'back', 'width'],
    videoKeyword: 'vertical traction machine lat',
  },

  {
    id: 'cable-woodchop',
    name: 'Cable Woodchop',
    target: ['obliques', 'abs'],
    secondary: ['core'],
    equipment: ['cable'],
    difficulty: 'beginner',
    tier: 'A',
    hypertrophyRating: 7,
    stimulusToFatigue: 8,
    description: 'High-tension anti-rotation movement targeting the obliques and lateral core. Great for stubborn love-handles.',
    executionNotes: [
      'Stand side-on to the cable column.',
      'Rotate the torso while maintaining a braced core.',
      'Control the eccentric and focus on oblique contraction.',
    ],
    alternatives: ['russian-twist-weighted', 'side-plank-hip-dip'],
    tags: ['obliques', 'core', 'rotation'],
    videoKeyword: 'cable woodchop obliques',
  },

  {
    id: 'russian-twist-weighted',
    name: 'Weighted Russian Twist',
    target: ['obliques', 'abs'],
    secondary: ['core'],
    equipment: ['plate', 'dumbbell'],
    difficulty: 'beginner',
    tier: 'B',
    hypertrophyRating: 7,
    stimulusToFatigue: 8,
    description: 'Rotational overload for obliques using a plate or dumbbell. High-rep finishing movement for love-handle reduction.',
    executionNotes: [
      'Sit slightly reclined with heels on the floor.',
      'Rotate under control and avoid momentum.',
      'Use a moderate load for 16–24 reps per set.',
    ],
    alternatives: ['cable-woodchop', 'side-plank-hip-dip'],
    tags: ['obliques', 'core', 'rotation', 'weighted'],
    videoKeyword: 'russian twist weighted',
  },

  {
    id: 'back-extension',
    name: 'Back Extension / Hyperextension',
    target: ['lower-back'],
    secondary: ['glutes', 'hamstrings'],
    equipment: ['machine'],
    difficulty: 'beginner',
    tier: 'A',
    hypertrophyRating: 8,
    stimulusToFatigue: 7,
    description: 'Targeted lower-back strengthening and hypertrophy exercise. Use progressive loading or pause at top for increased tension.',
    executionNotes: [
      'Align hips with pad pivot and avoid hyperextension at the top.',
      'Squeeze glutes and extend to neutral spine.',
      'Add plate/dumbbell on chest for progressive overload.',
    ],
    alternatives: ['good-morning', 'romanian-deadlift'],
    tags: ['lower-back', 'posterior-chain', 'machine'],
    videoKeyword: 'back extension hyperextension',
  },

  // ─── SHOULDERS ──────────────────────────────────────────────────────────

  {
    id: 'db-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    target: ['lateral-delts'],
    secondary: ['front-delts'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    tier: 'A',
    hypertrophyRating: 7,
    stimulusToFatigue: 9,
    description: 'Classic lateral delt builder. Limited stretch but high contraction stimulus.',
    executionNotes: [
      'Slight forward torso lean (15°) to improve lateral delt activation.',
      'Raise to just above shoulder height — arms parallel.',
      'Lead with elbows, not wrists.',
      'Keep slight bend in elbow throughout.',
    ],
    alternatives: ['cable-lateral-raise', 'machine-lateral-raise', 'leaning-lateral'],
    tags: ['isolation', 'lateral-delts', 'shoulders', 'dumbbell'],
    videoKeyword: 'lateral raise lateral delt',
  },

  {
    id: 'cable-lateral-raise',
    name: 'Cable Lateral Raise',
    target: ['lateral-delts'],
    secondary: ['front-delts'],
    equipment: ['cable'],
    difficulty: 'beginner',
    tier: 'S',
    hypertrophyRating: 9,
    stimulusToFatigue: 10,
    description: 'Superior to dumbbell raises due to constant tension throughout full ROM, especially at the stretched position.',
    executionNotes: [
      'Set cable at ankle height, cross body or same side.',
      'Raise across body until arm is parallel to ground.',
      'Slow controlled eccentric — 3 seconds down.',
      'The stretch (arm across body) is where the growth is.',
    ],
    alternatives: ['db-lateral-raise', 'machine-lateral-raise', 'leaning-lateral'],
    tags: ['isolation', 'lateral-delts', 'cable', 'stretch-mediated'],
    videoKeyword: 'cable lateral raise shoulder',
  },

  {
    id: 'leaning-lateral-raise',
    name: 'Leaning Cable Lateral Raise',
    target: ['lateral-delts'],
    secondary: [],
    equipment: ['cable'],
    difficulty: 'intermediate',
    tier: 'S',
    hypertrophyRating: 10,
    stimulusToFatigue: 10,
    description: 'Maximum lat delt stretch. Lean away from cable creating a huge stretch at the bottom. Best lateral delt exercise by S:F ratio.',
    executionNotes: [
      'Hold cable tower, lean away to create stretch.',
      'Arm hangs below and crosses body at start.',
      'Raise laterally to parallel — squeeze.',
      '3 second eccentric is essential.',
    ],
    alternatives: ['cable-lateral-raise', 'db-lateral-raise'],
    tags: ['isolation', 'lateral-delts', 'cable', 'stretch-mediated'],
    videoKeyword: 'leaning cable lateral raise',
  },

  {
    id: 'db-overhead-press',
    name: 'Dumbbell Overhead Press',
    target: ['shoulders', 'front-delts', 'lateral-delts'],
    secondary: ['triceps', 'upper-back'],
    equipment: ['dumbbell'],
    difficulty: 'intermediate',
    tier: 'A',
    hypertrophyRating: 8,
    stimulusToFatigue: 7,
    description: 'Compound shoulder builder. Dumbbells allow better ROM and reduced shoulder strain vs barbell.',
    executionNotes: [
      'Start with dumbbells at shoulder level, palms facing forward.',
      'Press straight up — slight arc inward at top.',
      'Do not lock out hard — maintain tension.',
      'Control the descent, elbows at 45-60° to body.',
    ],
    alternatives: ['bb-ohp', 'smith-ohp', 'machine-shoulder-press'],
    tags: ['compound', 'shoulders', 'press', 'dumbbell'],
    videoKeyword: 'dumbbell overhead press',
  },

  {
    id: 'machine-shoulder-press',
    name: 'Machine Shoulder Press',
    target: ['shoulders', 'front-delts'],
    secondary: ['triceps', 'lateral-delts'],
    equipment: ['machine'],
    difficulty: 'beginner',
    tier: 'A',
    hypertrophyRating: 8,
    stimulusToFatigue: 8,
    description: 'Safe, effective shoulder press variant. Good for beginners and for high volume shoulder work.',
    executionNotes: [
      'Adjust seat so handles align with shoulders.',
      'Press through, slight pause at bottom stretch.',
      'Keep core tight, do not arch excessively.',
    ],
    alternatives: ['db-overhead-press', 'smith-ohp'],
    tags: ['compound', 'shoulders', 'machine', 'press'],
    videoKeyword: 'machine shoulder press',
  },

  {
    id: 'face-pull',
    name: 'Cable Face Pull',
    target: ['rear-delts', 'upper-back'],
    secondary: ['shoulders', 'biceps'],
    equipment: ['cable'],
    difficulty: 'beginner',
    tier: 'A',
    hypertrophyRating: 8,
    stimulusToFatigue: 9,
    description: 'Essential for rear delt and upper back health and development. Critical for shoulder balance and longevity.',
    executionNotes: [
      'Rope attachment at upper chest height.',
      'Pull to face level, externally rotating at the end.',
      'Hands should finish level with or above ears.',
      'High rep sets (15-25) work well for rear delts.',
    ],
    alternatives: ['db-rear-delt-fly', 'band-pull-apart', 'reverse-pec-deck'],
    tags: ['isolation', 'rear-delts', 'cable', 'shoulder-health'],
    videoKeyword: 'cable face pull rear delt',
  },

  {
    id: 'rear-delt-fly',
    name: 'Rear Delt Cable Fly',
    target: ['rear-delts'],
    secondary: ['upper-back'],
    equipment: ['cable'],
    difficulty: 'beginner',
    tier: 'A',
    hypertrophyRating: 8,
    stimulusToFatigue: 10,
    description: 'Excellent rear delt isolation. Constant cable tension through full range of motion.',
    executionNotes: [
      'Cables set at face height, cross-over grip.',
      'Arms start crossed in front of you.',
      'Open arms out wide — feel rear delt contract.',
      'Slow controlled return maximises hypertrophy.',
    ],
    alternatives: ['face-pull', 'db-rear-delt-fly', 'reverse-pec-deck'],
    tags: ['isolation', 'rear-delts', 'cable'],
    videoKeyword: 'rear delt cable fly',
  },

  // ─── BICEPS ─────────────────────────────────────────────────────────────

  {
    id: 'incline-db-curl',
    name: 'Incline Dumbbell Curl',
    target: ['biceps'],
    secondary: ['forearms'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    tier: 'S',
    hypertrophyRating: 10,
    stimulusToFatigue: 10,
    description: 'Best stretch-mediated bicep exercise. Long head bias and maximum stretch creates highest hypertrophic stimulus.',
    executionNotes: [
      'Set bench to 45-60°, lean back.',
      'Arms hang behind torso — this is the stretch.',
      'Curl without letting elbows drift forward.',
      '3-second eccentric is critical — resist the stretch.',
      'Do not swing or use momentum.',
    ],
    alternatives: ['cable-curl-low', 'bayesian-curl', 'preacher-curl'],
    tags: ['isolation', 'biceps', 'stretch-mediated', 'long-head'],
    videoKeyword: 'incline dumbbell curl bicep',
  },

  {
    id: 'cable-curl-low',
    name: 'Low Cable Curl',
    target: ['biceps'],
    secondary: ['forearms'],
    equipment: ['cable'],
    difficulty: 'beginner',
    tier: 'S',
    hypertrophyRating: 9,
    stimulusToFatigue: 10,
    description: 'Constant tension through full ROM. The stretch at the bottom loaded position is highly effective for hypertrophy.',
    executionNotes: [
      'Use rope or straight bar at ankle height.',
      'Stand far back to feel stretch at the bottom.',
      'Curl to chin level — elbows stay at sides.',
      'Control the eccentric fully.',
    ],
    alternatives: ['incline-db-curl', 'bayesian-curl', 'ez-bar-curl'],
    tags: ['isolation', 'biceps', 'cable', 'stretch-mediated'],
    videoKeyword: 'low cable curl bicep',
  },

  {
    id: 'ez-bar-curl',
    name: 'EZ Bar Curl',
    target: ['biceps'],
    secondary: ['forearms', 'brachialis'],
    equipment: ['ez-bar'],
    difficulty: 'beginner',
    tier: 'A',
    hypertrophyRating: 8,
    stimulusToFatigue: 7,
    description: 'Heavy bilateral bicep curl. Good for strength and mass building.',
    executionNotes: [
      'Use slight angled grip — easier on wrists than straight bar.',
      'Curl to chin/shoulder level.',
      'Elbows should not drift forward excessively.',
    ],
    alternatives: ['bb-curl', 'db-curl', 'cable-curl-low'],
    tags: ['isolation', 'biceps', 'bilateral', 'ez-bar'],
    videoKeyword: 'ez bar curl',
  },

  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    target: ['biceps', 'forearms'],
    secondary: [],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    tier: 'A',
    hypertrophyRating: 7,
    stimulusToFatigue: 8,
    description: 'Brachialis and brachioradialis emphasis. Adds thickness and width to the arm peak.',
    executionNotes: [
      'Neutral grip (thumbs up) throughout.',
      'Can be done alternating or simultaneously.',
      'Do not swing — keep elbows stationary.',
    ],
    alternatives: ['cross-body-hammer-curl', 'rope-hammer-curl'],
    tags: ['isolation', 'biceps', 'forearms', 'brachialis'],
    videoKeyword: 'hammer curl brachialis',
  },

  // ─── TRICEPS ────────────────────────────────────────────────────────────

  {
    id: 'overhead-tricep-extension',
    name: 'Cable Overhead Tricep Extension',
    target: ['triceps'],
    secondary: [],
    equipment: ['cable'],
    difficulty: 'beginner',
    tier: 'S',
    hypertrophyRating: 10,
    stimulusToFatigue: 10,
    description: 'Best tricep exercise for hypertrophy. Overhead position puts the long head in maximum stretch — highest S:F ratio.',
    executionNotes: [
      'Set cable at high pulley, use rope attachment.',
      'Hinge forward at hips, elbows near ears.',
      'Extend arms fully overhead — squeeze at top.',
      '3-second eccentric, feel the long head stretch.',
      'Do not let elbows flare out wide.',
    ],
    alternatives: ['db-overhead-ext', 'skull-crusher', 'bayesian-tricep'],
    tags: ['isolation', 'triceps', 'cable', 'stretch-mediated', 'long-head'],
    videoKeyword: 'cable overhead tricep extension',
  },

  {
    id: 'skull-crusher',
    name: 'EZ Bar Skull Crusher',
    target: ['triceps'],
    secondary: [],
    equipment: ['ez-bar'],
    difficulty: 'intermediate',
    tier: 'S',
    hypertrophyRating: 9,
    stimulusToFatigue: 8,
    description: 'Heavy tricep compound. Excellent for all three heads with significant long head stretch.',
    executionNotes: [
      'Lie flat, lower bar to forehead with slow eccentric.',
      'Keep upper arms vertical — only forearms move.',
      'Use EZ bar to reduce wrist strain.',
      'Slow down the eccentric — 3-4 seconds.',
    ],
    alternatives: ['overhead-tricep-extension', 'db-skull-crusher'],
    tags: ['isolation', 'triceps', 'compound', 'strength'],
    videoKeyword: 'skull crusher tricep',
  },

  {
    id: 'tricep-pushdown',
    name: 'Cable Tricep Pushdown (Rope)',
    target: ['triceps'],
    secondary: [],
    equipment: ['cable'],
    difficulty: 'beginner',
    tier: 'A',
    hypertrophyRating: 8,
    stimulusToFatigue: 9,
    description: 'Excellent pump and lateral head work. High volume burnout exercise.',
    executionNotes: [
      'Use rope attachment — split hands apart at bottom.',
      'Keep elbows tucked to sides throughout.',
      'Fully extend and squeeze at bottom.',
      'Works well in high rep ranges (12-20).',
    ],
    alternatives: ['overhead-tricep-extension', 'skull-crusher', 'tricep-kickback'],
    tags: ['isolation', 'triceps', 'cable', 'lateral-head', 'pump'],
    videoKeyword: 'cable tricep pushdown rope',
  },

  // ─── QUADS ──────────────────────────────────────────────────────────────

  {
    id: 'hack-squat',
    name: 'Hack Squat',
    target: ['quads'],
    secondary: ['glutes', 'hamstrings'],
    equipment: ['machine'],
    difficulty: 'intermediate',
    tier: 'S',
    hypertrophyRating: 10,
    stimulusToFatigue: 8,
    description: 'Best quad hypertrophy machine. Higher quad bias than squats, safer spine loading.',
    executionNotes: [
      'Feet shoulder-width, lower on the pad.',
      'Squat deep — thighs below parallel.',
      'Drive through heels, feel the quads.',
      'Pause at the bottom for maximum stretch.',
    ],
    alternatives: ['leg-press', 'db-squat', 'bulgarian-split-squat'],
    tags: ['compound', 'quads', 'machine', 'legs'],
    videoKeyword: 'hack squat quad hypertrophy',
  },

  {
    id: 'leg-press',
    name: 'Leg Press',
    target: ['quads', 'glutes'],
    secondary: ['hamstrings'],
    equipment: ['machine'],
    difficulty: 'beginner',
    tier: 'A',
    hypertrophyRating: 8,
    stimulusToFatigue: 7,
    description: 'Safe, loadable quad builder. Foot placement changes muscle emphasis.',
    executionNotes: [
      'Feet low on platform for more quad emphasis.',
      'Full range of motion — do not half-rep.',
      'Do not let knees cave inward.',
      'Slow and controlled on the way down.',
    ],
    alternatives: ['hack-squat', 'squat', 'smith-squat'],
    tags: ['compound', 'quads', 'machine', 'legs'],
    videoKeyword: 'leg press quad',
  },

  {
    id: 'leg-extension',
    name: 'Leg Extension',
    target: ['quads'],
    secondary: [],
    equipment: ['machine'],
    difficulty: 'beginner',
    tier: 'A',
    hypertrophyRating: 8,
    stimulusToFatigue: 9,
    description: 'Best quad isolation. Especially good for the rectus femoris with hip flexed position.',
    executionNotes: [
      'Adjust seat back so knee aligns with pivot.',
      'Extend fully — pause and squeeze at top.',
      'Slow the descent — 3 seconds.',
      'Toes can be turned in for VMO emphasis.',
    ],
    alternatives: ['sissy-squat', 'spanish-squat'],
    tags: ['isolation', 'quads', 'machine'],
    videoKeyword: 'leg extension quad isolation',
  },

  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    target: ['quads', 'glutes'],
    secondary: ['hamstrings'],
    equipment: ['dumbbell', 'barbell'],
    difficulty: 'advanced',
    tier: 'S',
    hypertrophyRating: 9,
    stimulusToFatigue: 7,
    description: 'Elite unilateral quad and glute builder. Massive stretch at the bottom. High neural demand.',
    executionNotes: [
      'Rear foot elevated on bench behind you.',
      'Front foot far enough forward to keep shin vertical at bottom.',
      'Lower until rear knee nearly touches floor.',
      'Drive through front heel, squeeze glute at top.',
    ],
    alternatives: ['hack-squat', 'leg-press', 'walking-lunge'],
    tags: ['compound', 'quads', 'glutes', 'unilateral', 'stretch-mediated'],
    videoKeyword: 'bulgarian split squat',
  },

  // ─── HAMSTRINGS / GLUTES ────────────────────────────────────────────────

  {
    id: 'hip-thrust',
    name: 'Barbell Hip Thrust',
    target: ['glutes', 'hamstrings'],
    secondary: ['lower-back'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    tier: 'S',
    hypertrophyRating: 10,
    stimulusToFatigue: 9,
    description: 'Best glute hypertrophy exercise — peak contraction loading without spinal flexion. No hip-hinge pattern required.',
    executionNotes: [
      'Upper back braced against a bench, barbell over hips (pad recommended).',
      'Feet flat, shins roughly vertical at the top.',
      'Drive through heels, squeeze glutes hard at lockout.',
      'Pause 1-2 seconds at the top for peak contraction.',
      'Lower under control — do not let hips drop fast.',
    ],
    alternatives: ['lying-leg-curl', 'leg-press', 'bulgarian-split-squat'],
    tags: ['compound', 'glutes', 'hamstrings', 'peak-contraction'],
    videoKeyword: 'barbell hip thrust glutes',
  },

  {
    id: 'lying-leg-curl',
    name: 'Lying Leg Curl',
    target: ['hamstrings'],
    secondary: [],
    equipment: ['machine'],
    difficulty: 'beginner',
    tier: 'A',
    hypertrophyRating: 8,
    stimulusToFatigue: 9,
    description: 'Best hamstring isolation machine. Full range of motion in both stretch and contraction.',
    executionNotes: [
      'Align knee with pivot point.',
      'Curl to full contraction — pause at top.',
      'Slow eccentric (3s) — do not drop the weight.',
      'Point toes for extra contraction at top.',
    ],
    alternatives: ['hip-thrust', 'seated-leg-curl', 'nordic-curl'],
    tags: ['isolation', 'hamstrings', 'machine'],
    videoKeyword: 'lying leg curl hamstring',
  },

  // ─── CORE ───────────────────────────────────────────────────────────────

  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    target: ['abs'],
    secondary: ['obliques'],
    equipment: ['cable'],
    difficulty: 'beginner',
    tier: 'S',
    hypertrophyRating: 9,
    stimulusToFatigue: 9,
    description: 'Best weighted ab exercise. Allows progressive overload on the rectus abdominis with constant tension.',
    executionNotes: [
      'Kneel facing cable stack, rope at forehead.',
      'Crunch down — round the spine, bring elbows to thighs.',
      'Do not use hip flexors — isolate the ab contraction.',
      'Hold contracted position 1 second.',
      'Progressive overload: increase weight each week.',
    ],
    alternatives: ['machine-crunch', 'weighted-decline-sit-up'],
    tags: ['isolation', 'abs', 'core', 'cable', 'weighted'],
    videoKeyword: 'cable crunch abs',
  },

  {
    id: 'hanging-leg-raise-weighted',
    name: 'Weighted Hanging Leg Raise',
    target: ['abs', 'core'],
    secondary: ['hip-flexors', 'obliques'],
    equipment: ['pull-up-bar'],
    difficulty: 'intermediate',
    tier: 'S',
    hypertrophyRating: 9,
    stimulusToFatigue: 8,
    description: 'Full range ab exercise from maximum stretch to peak contraction. Add weight via ankle weights or dumbbell.',
    executionNotes: [
      'Hang from bar, minimize swinging.',
      'Tuck pelvis at the top — this activates rectus.',
      'Raise legs to 90° minimum — higher is better.',
      'Lower slowly under control — do not drop.',
      'Add ankle weights when bodyweight becomes easy.',
    ],
    alternatives: ['cable-crunch', 'weighted-sit-up', 'dragon-flag'],
    tags: ['compound', 'abs', 'core', 'weighted', 'stretch-mediated'],
    videoKeyword: 'hanging leg raise weighted abs',
  },

  {
    id: 'weighted-sit-up',
    name: 'Weighted Sit-Up',
    target: ['abs'],
    secondary: ['hip-flexors'],
    equipment: ['dumbbell', 'barbell'],
    difficulty: 'beginner',
    tier: 'A',
    hypertrophyRating: 8,
    stimulusToFatigue: 8,
    description: 'Simple, effective, overloadable ab exercise. Anchor feet for hip flexor involvement or free for ab isolation.',
    executionNotes: [
      'Hold weight at chest or extended overhead.',
      'Full range of motion — shoulders to floor.',
      'Control the eccentric descent.',
      'Overhead loading increases difficulty significantly.',
    ],
    alternatives: ['cable-crunch', 'decline-sit-up'],
    tags: ['compound', 'abs', 'weighted'],
    videoKeyword: 'weighted sit up abs',
  },

  {
    id: 'pallof-press',
    name: 'Pallof Press',
    target: ['core', 'obliques'],
    secondary: ['abs'],
    equipment: ['cable', 'band'],
    difficulty: 'beginner',
    tier: 'A',
    hypertrophyRating: 7,
    stimulusToFatigue: 9,
    description: 'Anti-rotation core exercise. Trains core stability and resisting rotational force — critical for functional strength.',
    executionNotes: [
      'Stand perpendicular to cable, chest height.',
      'Press out and resist the pull — do not rotate.',
      'Pause fully extended for 2 seconds.',
      'Keep hips square and steady.',
    ],
    alternatives: ['plank', 'cable-crunch', 'bird-dog'],
    tags: ['stability', 'core', 'obliques', 'anti-rotation'],
    videoKeyword: 'pallof press core',
  },

  // ─── CARDIO / CONDITIONING ─────────────────────────────────────────────

  {
    id: 'treadmill-run',
    name: 'Treadmill Interval Run',
    target: ['core'],
    secondary: ['calves'],
    equipment: ['machine'],
    difficulty: 'beginner',
    tier: 'A',
    hypertrophyRating: 1,
    stimulusToFatigue: 5,
    description: 'High-intensity intervals on the treadmill for conditioning and fat loss. Use a run/walk or sprint/jog protocol as appropriate.',
    executionNotes: [
      'Warm up 5 minutes at easy pace.',
      'Alternate 30–60s hard / 60–90s easy for 20–30 minutes.',
      'Maintain good posture and controlled breathing.',
    ],
    alternatives: [],
    tags: ['cardio', 'conditioning', 'intervals'],
    videoKeyword: 'treadmill interval workout',
  },

  {
    id: 'stair-climber',
    name: 'Stair Climber / StepMill',
    target: ['calves', 'glutes'],
    secondary: ['quads', 'core'],
    equipment: ['machine'],
    difficulty: 'beginner',
    tier: 'A',
    hypertrophyRating: 2,
    stimulusToFatigue: 6,
    description: 'Sustained stair climber work for conditioning and lower-body metabolic stimulus. Use steady-state or intervals.',
    executionNotes: [
      'Keep torso upright and step through full range.',
      'Use intervals for higher intensity: 1–2 min hard, 1 min easy.',
      'Focus on driving through the heel to emphasise glutes.',
    ],
    alternatives: [],
    tags: ['cardio', 'conditioning', 'legs'],
    videoKeyword: 'stair climber workout',
  },

  {
    id: 'dragon-flag',
    name: 'Dragon Flag Progression',
    target: ['abs', 'core'],
    secondary: ['lats', 'lower-back'],
    equipment: ['bodyweight'],
    difficulty: 'advanced',
    tier: 'A',
    hypertrophyRating: 8,
    stimulusToFatigue: 7,
    description: 'Advanced full-body core exercise. Builds extreme core strength and control.',
    executionNotes: [
      'Start with tuck position — progress to full straight body.',
      'Lower body slowly to near horizontal.',
      'Maintain rigid body position throughout.',
      'Use a bench or fixed surface to grip.',
      'Negatives only is fine for beginners.',
    ],
    alternatives: ['hanging-leg-raise-weighted', 'cable-crunch'],
    tags: ['advanced', 'abs', 'core', 'bodyweight'],
    videoKeyword: 'dragon flag progression',
  },
]

// ─── Lookup helpers ────────────────────────────────────────────────────────

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISES.find(e => e.id === id)
}

export function getExercisesByMuscle(muscle: string): Exercise[] {
  return EXERCISES.filter(e =>
    e.target.includes(muscle as any) || e.secondary.includes(muscle as any)
  )
}

export function getExercisesByTier(tier: 'S' | 'A' | 'B'): Exercise[] {
  return EXERCISES.filter(e => e.tier === tier)
}

export function getExercisesByEquipment(equipment: string[]): Exercise[] {
  return EXERCISES.filter(e =>
    e.equipment.some(eq => equipment.includes(eq))
  )
}

export function getAlternatives(exerciseId: string): Exercise[] {
  const exercise = getExerciseById(exerciseId)
  if (!exercise) return []
  return exercise.alternatives
    .map(id => getExerciseById(id))
    .filter(Boolean) as Exercise[]
}

export const MUSCLE_GROUPS = [
  { id: 'upper-chest',   label: 'Upper Chest',    emoji: '💪' },
  { id: 'chest',         label: 'Chest',           emoji: '💪' },
  { id: 'lats',          label: 'Lats',            emoji: '🦅' },
  { id: 'back',          label: 'Back',            emoji: '🦅' },
  { id: 'lateral-delts', label: 'Lateral Delts',   emoji: '🏋️' },
  { id: 'shoulders',     label: 'Shoulders',       emoji: '🏋️' },
  { id: 'rear-delts',    label: 'Rear Delts',      emoji: '🏋️' },
  { id: 'biceps',        label: 'Biceps',          emoji: '💪' },
  { id: 'triceps',       label: 'Triceps',         emoji: '💪' },
  { id: 'quads',         label: 'Quads',           emoji: '🦵' },
  { id: 'hamstrings',    label: 'Hamstrings',      emoji: '🦵' },
  { id: 'glutes',        label: 'Glutes',          emoji: '🍑' },
  { id: 'abs',           label: 'Abs',             emoji: '⚡' },
  { id: 'core',          label: 'Core',            emoji: '⚡' },
]
